# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gloopy_pb2 as gloopy__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gloopy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GloopyStub:
    """── service ────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Play = channel.unary_unary(
                '/gloopy.v1.Gloopy/Play',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/gloopy.v1.Gloopy/Stop',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.SetTempo = channel.unary_unary(
                '/gloopy.v1.Gloopy/SetTempo',
                request_serializer=gloopy__pb2.Tempo.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.SetSwing = channel.unary_unary(
                '/gloopy.v1.Gloopy/SetSwing',
                request_serializer=gloopy__pb2.Swing.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.Seek = channel.unary_unary(
                '/gloopy.v1.Gloopy/Seek',
                request_serializer=gloopy__pb2.Position.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.GetTransport = channel.unary_unary(
                '/gloopy.v1.Gloopy/GetTransport',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.TransportState.FromString,
                _registered_method=True)
        self.StartRecording = channel.unary_unary(
                '/gloopy.v1.Gloopy/StartRecording',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.StopRecording = channel.unary_unary(
                '/gloopy.v1.Gloopy/StopRecording',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.AddSynthTrack = channel.unary_unary(
                '/gloopy.v1.Gloopy/AddSynthTrack',
                request_serializer=gloopy__pb2.AddSynthTrackRequest.SerializeToString,
                response_deserializer=gloopy__pb2.TrackId.FromString,
                _registered_method=True)
        self.SetTrackParams = channel.unary_unary(
                '/gloopy.v1.Gloopy/SetTrackParams',
                request_serializer=gloopy__pb2.TrackParams.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.SetSynthParam = channel.unary_unary(
                '/gloopy.v1.Gloopy/SetSynthParam',
                request_serializer=gloopy__pb2.SynthParamSet.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.ListTracks = channel.unary_unary(
                '/gloopy.v1.Gloopy/ListTracks',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.TrackList.FromString,
                _registered_method=True)
        self.AddClip = channel.unary_unary(
                '/gloopy.v1.Gloopy/AddClip',
                request_serializer=gloopy__pb2.AddClipRequest.SerializeToString,
                response_deserializer=gloopy__pb2.ClipId.FromString,
                _registered_method=True)
        self.RemoveTrack = channel.unary_unary(
                '/gloopy.v1.Gloopy/RemoveTrack',
                request_serializer=gloopy__pb2.TrackId.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.AddAudioTrack = channel.unary_unary(
                '/gloopy.v1.Gloopy/AddAudioTrack',
                request_serializer=gloopy__pb2.AddAudioTrackRequest.SerializeToString,
                response_deserializer=gloopy__pb2.TrackId.FromString,
                _registered_method=True)
        self.AddSamplerTrack = channel.unary_unary(
                '/gloopy.v1.Gloopy/AddSamplerTrack',
                request_serializer=gloopy__pb2.AddSamplerTrackRequest.SerializeToString,
                response_deserializer=gloopy__pb2.TrackId.FromString,
                _registered_method=True)
        self.AddPluginTrack = channel.unary_unary(
                '/gloopy.v1.Gloopy/AddPluginTrack',
                request_serializer=gloopy__pb2.AddPluginTrackRequest.SerializeToString,
                response_deserializer=gloopy__pb2.TrackId.FromString,
                _registered_method=True)
        self.RemoveClip = channel.unary_unary(
                '/gloopy.v1.Gloopy/RemoveClip',
                request_serializer=gloopy__pb2.ClipRef.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.MoveClip = channel.unary_unary(
                '/gloopy.v1.Gloopy/MoveClip',
                request_serializer=gloopy__pb2.MoveClipRequest.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.AddAudioClip = channel.unary_unary(
                '/gloopy.v1.Gloopy/AddAudioClip',
                request_serializer=gloopy__pb2.AddAudioClipRequest.SerializeToString,
                response_deserializer=gloopy__pb2.ClipId.FromString,
                _registered_method=True)
        self.ScanPlugins = channel.unary_unary(
                '/gloopy.v1.Gloopy/ScanPlugins',
                request_serializer=gloopy__pb2.ScanPluginsRequest.SerializeToString,
                response_deserializer=gloopy__pb2.PluginList.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/gloopy.v1.Gloopy/ListPlugins',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.PluginList.FromString,
                _registered_method=True)
        self.AddPluginEffect = channel.unary_unary(
                '/gloopy.v1.Gloopy/AddPluginEffect',
                request_serializer=gloopy__pb2.AddPluginEffectRequest.SerializeToString,
                response_deserializer=gloopy__pb2.EffectRef.FromString,
                _registered_method=True)
        self.OpenPluginEditor = channel.unary_unary(
                '/gloopy.v1.Gloopy/OpenPluginEditor',
                request_serializer=gloopy__pb2.TrackId.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.ListInserts = channel.unary_unary(
                '/gloopy.v1.Gloopy/ListInserts',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.InsertList.FromString,
                _registered_method=True)
        self.SetInsertParams = channel.unary_unary(
                '/gloopy.v1.Gloopy/SetInsertParams',
                request_serializer=gloopy__pb2.InsertParams.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.AddEffect = channel.unary_unary(
                '/gloopy.v1.Gloopy/AddEffect',
                request_serializer=gloopy__pb2.AddEffectRequest.SerializeToString,
                response_deserializer=gloopy__pb2.EffectRef.FromString,
                _registered_method=True)
        self.RemoveEffect = channel.unary_unary(
                '/gloopy.v1.Gloopy/RemoveEffect',
                request_serializer=gloopy__pb2.EffectRef.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.SetEffectParam = channel.unary_unary(
                '/gloopy.v1.Gloopy/SetEffectParam',
                request_serializer=gloopy__pb2.EffectParamSet.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.SetEffectBypass = channel.unary_unary(
                '/gloopy.v1.Gloopy/SetEffectBypass',
                request_serializer=gloopy__pb2.EffectBypassSet.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.GetEffectParams = channel.unary_unary(
                '/gloopy.v1.Gloopy/GetEffectParams',
                request_serializer=gloopy__pb2.EffectRef.SerializeToString,
                response_deserializer=gloopy__pb2.ParamList.FromString,
                _registered_method=True)
        self.SetAutomation = channel.unary_unary(
                '/gloopy.v1.Gloopy/SetAutomation',
                request_serializer=gloopy__pb2.Automation.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.GetAutomation = channel.unary_unary(
                '/gloopy.v1.Gloopy/GetAutomation',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.AutomationList.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/gloopy.v1.Gloopy/GetState',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.ProjectState.FromString,
                _registered_method=True)
        self.NewProject = channel.unary_unary(
                '/gloopy.v1.Gloopy/NewProject',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.Undo = channel.unary_unary(
                '/gloopy.v1.Gloopy/Undo',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.Redo = channel.unary_unary(
                '/gloopy.v1.Gloopy/Redo',
                request_serializer=gloopy__pb2.Empty.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.LoadProject = channel.unary_unary(
                '/gloopy.v1.Gloopy/LoadProject',
                request_serializer=gloopy__pb2.FilePath.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.SaveProject = channel.unary_unary(
                '/gloopy.v1.Gloopy/SaveProject',
                request_serializer=gloopy__pb2.FilePath.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.RenderToFile = channel.unary_unary(
                '/gloopy.v1.Gloopy/RenderToFile',
                request_serializer=gloopy__pb2.RenderRequest.SerializeToString,
                response_deserializer=gloopy__pb2.Ack.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/gloopy.v1.Gloopy/Subscribe',
                request_serializer=gloopy__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=gloopy__pb2.Event.FromString,
                _registered_method=True)


class GloopyServicer:
    """── service ────────────────────────────────────────────────
    """

    def Play(self, request, context):
        """transport
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTempo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSwing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Seek(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRecording(self, request, context):
        """record played MIDI into the armed track
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSynthTrack(self, request, context):
        """tracks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTrackParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSynthParam(self, request, context):
        """tweak the built-in synth engine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTracks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddClip(self, request, context):
        """clips & notes (programmatic sequences)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTrack(self, request, context):
        """track & clip management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAudioTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSamplerTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPluginTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveClip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveClip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAudioClip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanPlugins(self, request, context):
        """plugins
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPluginEffect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenPluginEditor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInserts(self, request, context):
        """mixer & effects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInsertParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEffect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveEffect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEffectParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEffectBypass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEffectParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAutomation(self, request, context):
        """automation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAutomation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """project & state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Undo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Redo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderToFile(self, request, context):
        """offline bounce to WAV
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """events (playhead, meters) — closed-loop control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GloopyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Play': grpc.unary_unary_rpc_method_handler(
                    servicer.Play,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'SetTempo': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTempo,
                    request_deserializer=gloopy__pb2.Tempo.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'SetSwing': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSwing,
                    request_deserializer=gloopy__pb2.Swing.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'Seek': grpc.unary_unary_rpc_method_handler(
                    servicer.Seek,
                    request_deserializer=gloopy__pb2.Position.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'GetTransport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransport,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.TransportState.SerializeToString,
            ),
            'StartRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRecording,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'StopRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRecording,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'AddSynthTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSynthTrack,
                    request_deserializer=gloopy__pb2.AddSynthTrackRequest.FromString,
                    response_serializer=gloopy__pb2.TrackId.SerializeToString,
            ),
            'SetTrackParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrackParams,
                    request_deserializer=gloopy__pb2.TrackParams.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'SetSynthParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSynthParam,
                    request_deserializer=gloopy__pb2.SynthParamSet.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'ListTracks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTracks,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.TrackList.SerializeToString,
            ),
            'AddClip': grpc.unary_unary_rpc_method_handler(
                    servicer.AddClip,
                    request_deserializer=gloopy__pb2.AddClipRequest.FromString,
                    response_serializer=gloopy__pb2.ClipId.SerializeToString,
            ),
            'RemoveTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTrack,
                    request_deserializer=gloopy__pb2.TrackId.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'AddAudioTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAudioTrack,
                    request_deserializer=gloopy__pb2.AddAudioTrackRequest.FromString,
                    response_serializer=gloopy__pb2.TrackId.SerializeToString,
            ),
            'AddSamplerTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSamplerTrack,
                    request_deserializer=gloopy__pb2.AddSamplerTrackRequest.FromString,
                    response_serializer=gloopy__pb2.TrackId.SerializeToString,
            ),
            'AddPluginTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPluginTrack,
                    request_deserializer=gloopy__pb2.AddPluginTrackRequest.FromString,
                    response_serializer=gloopy__pb2.TrackId.SerializeToString,
            ),
            'RemoveClip': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveClip,
                    request_deserializer=gloopy__pb2.ClipRef.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'MoveClip': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveClip,
                    request_deserializer=gloopy__pb2.MoveClipRequest.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'AddAudioClip': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAudioClip,
                    request_deserializer=gloopy__pb2.AddAudioClipRequest.FromString,
                    response_serializer=gloopy__pb2.ClipId.SerializeToString,
            ),
            'ScanPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanPlugins,
                    request_deserializer=gloopy__pb2.ScanPluginsRequest.FromString,
                    response_serializer=gloopy__pb2.PluginList.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.PluginList.SerializeToString,
            ),
            'AddPluginEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPluginEffect,
                    request_deserializer=gloopy__pb2.AddPluginEffectRequest.FromString,
                    response_serializer=gloopy__pb2.EffectRef.SerializeToString,
            ),
            'OpenPluginEditor': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenPluginEditor,
                    request_deserializer=gloopy__pb2.TrackId.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'ListInserts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInserts,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.InsertList.SerializeToString,
            ),
            'SetInsertParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInsertParams,
                    request_deserializer=gloopy__pb2.InsertParams.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'AddEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEffect,
                    request_deserializer=gloopy__pb2.AddEffectRequest.FromString,
                    response_serializer=gloopy__pb2.EffectRef.SerializeToString,
            ),
            'RemoveEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveEffect,
                    request_deserializer=gloopy__pb2.EffectRef.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'SetEffectParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEffectParam,
                    request_deserializer=gloopy__pb2.EffectParamSet.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'SetEffectBypass': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEffectBypass,
                    request_deserializer=gloopy__pb2.EffectBypassSet.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'GetEffectParams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEffectParams,
                    request_deserializer=gloopy__pb2.EffectRef.FromString,
                    response_serializer=gloopy__pb2.ParamList.SerializeToString,
            ),
            'SetAutomation': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAutomation,
                    request_deserializer=gloopy__pb2.Automation.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'GetAutomation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAutomation,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.AutomationList.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.ProjectState.SerializeToString,
            ),
            'NewProject': grpc.unary_unary_rpc_method_handler(
                    servicer.NewProject,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'Undo': grpc.unary_unary_rpc_method_handler(
                    servicer.Undo,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'Redo': grpc.unary_unary_rpc_method_handler(
                    servicer.Redo,
                    request_deserializer=gloopy__pb2.Empty.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'LoadProject': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadProject,
                    request_deserializer=gloopy__pb2.FilePath.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'SaveProject': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveProject,
                    request_deserializer=gloopy__pb2.FilePath.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'RenderToFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderToFile,
                    request_deserializer=gloopy__pb2.RenderRequest.FromString,
                    response_serializer=gloopy__pb2.Ack.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=gloopy__pb2.SubscribeRequest.FromString,
                    response_serializer=gloopy__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gloopy.v1.Gloopy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gloopy.v1.Gloopy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gloopy:
    """── service ────────────────────────────────────────────────
    """

    @staticmethod
    def Play(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/Play',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/Stop',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTempo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/SetTempo',
            gloopy__pb2.Tempo.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSwing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/SetSwing',
            gloopy__pb2.Swing.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Seek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/Seek',
            gloopy__pb2.Position.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/GetTransport',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.TransportState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/StartRecording',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/StopRecording',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSynthTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/AddSynthTrack',
            gloopy__pb2.AddSynthTrackRequest.SerializeToString,
            gloopy__pb2.TrackId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTrackParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/SetTrackParams',
            gloopy__pb2.TrackParams.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSynthParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/SetSynthParam',
            gloopy__pb2.SynthParamSet.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTracks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/ListTracks',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.TrackList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddClip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/AddClip',
            gloopy__pb2.AddClipRequest.SerializeToString,
            gloopy__pb2.ClipId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/RemoveTrack',
            gloopy__pb2.TrackId.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAudioTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/AddAudioTrack',
            gloopy__pb2.AddAudioTrackRequest.SerializeToString,
            gloopy__pb2.TrackId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSamplerTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/AddSamplerTrack',
            gloopy__pb2.AddSamplerTrackRequest.SerializeToString,
            gloopy__pb2.TrackId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPluginTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/AddPluginTrack',
            gloopy__pb2.AddPluginTrackRequest.SerializeToString,
            gloopy__pb2.TrackId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveClip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/RemoveClip',
            gloopy__pb2.ClipRef.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveClip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/MoveClip',
            gloopy__pb2.MoveClipRequest.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAudioClip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/AddAudioClip',
            gloopy__pb2.AddAudioClipRequest.SerializeToString,
            gloopy__pb2.ClipId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/ScanPlugins',
            gloopy__pb2.ScanPluginsRequest.SerializeToString,
            gloopy__pb2.PluginList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/ListPlugins',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.PluginList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPluginEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/AddPluginEffect',
            gloopy__pb2.AddPluginEffectRequest.SerializeToString,
            gloopy__pb2.EffectRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenPluginEditor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/OpenPluginEditor',
            gloopy__pb2.TrackId.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInserts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/ListInserts',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.InsertList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetInsertParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/SetInsertParams',
            gloopy__pb2.InsertParams.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/AddEffect',
            gloopy__pb2.AddEffectRequest.SerializeToString,
            gloopy__pb2.EffectRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/RemoveEffect',
            gloopy__pb2.EffectRef.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEffectParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/SetEffectParam',
            gloopy__pb2.EffectParamSet.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEffectBypass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/SetEffectBypass',
            gloopy__pb2.EffectBypassSet.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEffectParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/GetEffectParams',
            gloopy__pb2.EffectRef.SerializeToString,
            gloopy__pb2.ParamList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAutomation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/SetAutomation',
            gloopy__pb2.Automation.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAutomation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/GetAutomation',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.AutomationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/GetState',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.ProjectState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/NewProject',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Undo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/Undo',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Redo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/Redo',
            gloopy__pb2.Empty.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/LoadProject',
            gloopy__pb2.FilePath.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/SaveProject',
            gloopy__pb2.FilePath.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderToFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gloopy.v1.Gloopy/RenderToFile',
            gloopy__pb2.RenderRequest.SerializeToString,
            gloopy__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gloopy.v1.Gloopy/Subscribe',
            gloopy__pb2.SubscribeRequest.SerializeToString,
            gloopy__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
