id = "lead"
name = "Lead"
type = 0
colour = -2536838
default_pitch = 69
volume = 0.60000002384185791
pan = 0.18000000715255737
mute = false
solo = false
mixer_insert = "ins-7"

[generator]
type = "synth"
wave = 2
attack = 0.004999999888241291
decay = 0.18000000715255737
sustain = 0.60000002384185791
release = 0.25
gain = 0.18000000715255737
osc2wave = 1
osc2detune = 0
oscmix = 0
sub = 0
ftype = 0
cutoff = 20000
reso = 0.69999998807907104
fenvamt = 0
fattack = 0.0099999997764825821
fdecay = 0.20000000298023224
fsustain = 0.60000002384185791
frelease = 0.30000001192092896
lfotarget = 0
lforate = 5
lfodepth = 0

[[clips]]
id = "lead"
name = "Lead"
ctype = 0
start = 64
length = 32
content_length = 16
looped = true
notes = "clips/lead/lead.notes"

[[clips]]
id = "lead-2"
name = "Lead"
ctype = 0
start = 128
length = 32
content_length = 16
looped = true
notes = "clips/lead/lead-2.notes"

[[clips]]
id = "lead-3"
name = "Lead"
ctype = 0
start = 192
length = 32
content_length = 16
looped = true
notes = "clips/lead/lead-3.notes"
