id = "hat"
name = "Hat"
type = 0
colour = -8388652
default_pitch = 60
volume = 0.2800000011920929
pan = 0
mute = false
solo = false
mixer_insert = "ins-3"

[generator]
type = "sampler"
sample_file = "assets/samples/hat.wav"
root = 60
sample_name = "Hat"
rate = 44100

[[clips]]
id = "hat"
name = "Hat"
ctype = 0
start = 0
length = 96
content_length = 96
looped = false
notes = "clips/hat/hat.notes"
