id = "kick"
name = "Kick"
type = 0
colour = -47872
default_pitch = 60
volume = 0.69999998807907104
pan = 0
mute = false
solo = false
mixer_insert = "ins-1"

[generator]
type = "sampler"
sample_file = "assets/samples/kick.wav"
root = 60
sample_name = "Kick"
rate = 44100

[[clips]]
id = "kick"
name = "Kick"
ctype = 0
start = 0
length = 128
content_length = 128
looped = false
notes = "clips/kick/kick.notes"
