id = "piano"
name = "Piano"
type = 0
colour = -11095445
default_pitch = 60
volume = 0.93999999761581421
pan = 0
mute = false
solo = false
mixer_insert = "ins-3"

[generator]
type = "sfz"
path = "SalamanderGrandPianoV3_OggVorbis/SalamanderGrandPianoV3.sfz"

[[clips]]
id = "piano"
name = "Piano"
ctype = 0
start = 0
length = 96
content_length = 96
looped = false
notes = "clips/piano/piano.notes"
