id = "kick"
name = "Kick"
type = 0
colour = -2070982
default_pitch = 60
volume = 0.89999997615814209
pan = 0
mute = false
solo = false
mixer_insert = "ins-1"

[generator]
type = "sampler"
sample_file = "assets/samples/kick.wav"
root = 60
sample_name = "kick"
rate = 44100

[[clips]]
id = "kick"
name = "Kick"
ctype = 0
start = 32
length = 32
content_length = 4
looped = true
notes = "clips/kick/kick.notes"

[[clips]]
id = "kick-2"
name = "Kick"
ctype = 0
start = 64
length = 32
content_length = 4
looped = true
notes = "clips/kick/kick-2.notes"

[[clips]]
id = "kick-3"
name = "Kick"
ctype = 0
start = 96
length = 64
content_length = 4
looped = true
notes = "clips/kick/kick-3.notes"

[[clips]]
id = "kick-4"
name = "Kick"
ctype = 0
start = 192
length = 32
content_length = 4
looped = true
notes = "clips/kick/kick-4.notes"
