id = "bass-drum"
tid = 6
name = "Bass Drum"
type = 0
colour = -12930876
default_pitch = 60
volume = 0.89999997615814209
pan = 0
mute = false
solo = false
mixer_insert = "ins-6"

[generator]
type = "sfz"
path = "Virtual-Playing-Orchestra3/Percussion/bassdrum.sfz"

[[clips]]
id = "bass-drum"
name = "Bass Drum"
ctype = 0
start = 0
length = 160
content_length = 160
looped = false
notes = "clips/bass-drum/bass-drum.notes"
