id = "cymbals"
tid = 7
name = "Cymbals"
type = 0
colour = -2536838
default_pitch = 60
volume = 0.55000001192092896
pan = 0.10000000149011612
mute = false
solo = false
mixer_insert = "ins-7"

[generator]
type = "sfz"
path = "Virtual-Playing-Orchestra3/Percussion/cymbals.sfz"

[[clips]]
id = "cymbals"
name = "Cymbals"
ctype = 0
start = 0
length = 160
content_length = 160
looped = false
notes = "clips/cymbals/cymbals.notes"
