id = "tremolo-str"
name = "Tremolo Str"
type = 0
colour = -2513855
default_pitch = 60
volume = 0.41999998688697815
pan = 0
mute = false
solo = false
mixer_insert = "ins-2"

[generator]
type = "sfz"
path = "Virtual-Playing-Orchestra3/Strings/all-strings-SEC-tremolo.sfz"

[[clips]]
id = "tremolo-str"
name = "Tremolo Str"
ctype = 0
start = 0
length = 160
content_length = 160
looped = false
notes = "clips/tremolo-str/tremolo-str.notes"
